In [19]:
import pandas as pd

conditions = ["confirmed", "deaths", "recovered"]

def make_countrydf(condition, country)
    df = pd.read_csv(f"data/time_{condition}.csv")
    df = df.loc[df["Country/Region"] == country]
    df = df.drop(columns=["Province/State", "Country/Region", "Lat", "Long"]).sum().reset_index(name=condition)
    df = df.rename(columns={'index':"date"})
    return df

final_df = None

for condition in conditions:
    condition_df = make_countrydf(condition)
    if final_df is None:
        final_df = condition_df
    else:
        final_df = final_df.merge(condition_df)

         date  confirmed
0     1/22/20          0
1     1/23/20          0
2     1/24/20          0
3     1/25/20          0
4     1/26/20          0
...       ...        ...
1138   3/5/23          0
1139   3/6/23          0
1140   3/7/23          0
1141   3/8/23          0
1142   3/9/23          0

[1143 rows x 2 columns]